name: Check Discord Bot Status

on:
  workflow_dispatch:
    

jobs:
  check-bot-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check bot status
        run: python main.py
