name: Check Bot Status

on:
  workflow_dispatch:

jobs:
  check_bot_status:
    name: Check Bot Status
    runs-on: ubuntu-latest
    steps:
      - name: Check bot status
        run: curl -s -o /dev/null -w "%{http_code}" "https://discord.com/api/v6/users/658732840783052823/relationships"
      - name: Print result
        run: |
          if [ "$(cat $GITHUB_EVENT_PATH | jq -r .output)" -eq 200 ]; then
            echo "Bot is online"
          else
            echo "Bot is offline"
          fi
